"""Initial schema

Revision ID: c2da8cc55ce5
Revises: 
Create Date: 2026-07-16 10:59:45.243754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2da8cc55ce5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('government', 'private', 'medical_college', name='hospitaltypeenum'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('blood_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('available_units', sa.Integer(), nullable=True),
    sa.Column('reserved_units', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('donor_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_bank_id'), 'blood_bank', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'hospital_admin', 'doctor', 'nurse', 'ambulance_staff', name='roleenum'), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('medical_license_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('nurses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurses_id'), 'nurses', ['id'], unique=False)
    op.create_table('operating_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('available', 'occupied', 'reserved', 'cleaning', 'maintenance', name='resourcestatusenum'), nullable=True),
    sa.Column('current_surgery', sa.String(), nullable=True),
    sa.Column('assigned_surgeon_id', sa.Integer(), nullable=True),
    sa.Column('expected_completion_time', sa.DateTime(), nullable=True),
    sa.Column('available_equipment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_surgeon_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_rooms_id'), 'operating_rooms', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('current_disease', sa.String(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('insurance', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admission_time', sa.DateTime(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('assigned_doctor_id', sa.Integer(), nullable=True),
    sa.Column('assigned_nurse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['assigned_nurse_id'], ['nurses.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('emergency_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_doctor_id', sa.Integer(), nullable=True),
    sa.Column('assigned_ward', sa.String(), nullable=True),
    sa.Column('emergency_notes', sa.Text(), nullable=True),
    sa.Column('current_condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_queue_id'), 'emergency_queue', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('available', 'occupied', 'reserved', 'cleaning', 'maintenance', name='resourcestatusenum'), nullable=True),
    sa.Column('maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_patient_id', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('icu_beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('icu_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('available', 'occupied', 'reserved', 'cleaning', 'maintenance', name='resourcestatusenum'), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('ventilator', sa.Boolean(), nullable=True),
    sa.Column('cardiac_monitor', sa.Boolean(), nullable=True),
    sa.Column('assigned_nurse_id', sa.Integer(), nullable=True),
    sa.Column('assigned_patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_nurse_id'], ['nurses.id'], ),
    sa.ForeignKeyConstraint(['assigned_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icu_beds_id'), 'icu_beds', ['id'], unique=False)
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_number', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('driver', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('available', 'occupied', 'reserved', 'cleaning', 'maintenance', name='resourcestatusenum'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('assigned_case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_case_id'], ['emergency_queue.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_table('ambulances')
    op.drop_index(op.f('ix_icu_beds_id'), table_name='icu_beds')
    op.drop_table('icu_beds')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_emergency_queue_id'), table_name='emergency_queue')
    op.drop_table('emergency_queue')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_operating_rooms_id'), table_name='operating_rooms')
    op.drop_table('operating_rooms')
    op.drop_index(op.f('ix_nurses_id'), table_name='nurses')
    op.drop_table('nurses')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_blood_bank_id'), table_name='blood_bank')
    op.drop_table('blood_bank')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
